# Reinforcement Learning
The next and final topic in this course covers Reinforcement Learning.This technique is different than many of the other machine learning
techniques we have seen earlier and has many applications in training agents(an Al)to interact with enviornments like games.Rather than
feeding our machine learning model millions of examples we let our model come up with it's own examples by exploring an enviomnemt.The
concept is fairly simple. Humans learn by exploring and leaming from mistakes and past experiences so let's have our computer do the same.

# Terminology
Before we dive into explaining reinforcement learning we need to define a few key peices of terminology.
Enviornemt In reinforcement learning tasks we have a notion of the enviomment.This is what our agent will explore.An example of an
enviornment in the case of training an Al to play say a game of mario would be the level we are training the agent on
Agent an agent is an entity that is exploring the enviornment. Our agent will interact and take different actions within the enviornment.In our
mario example the mario character within the game would be our agent.
State at all times our agent will be in what we call a state.The state simply tells us about the status of the agent.The most common example of
a state is the location of the agent within the enviomment. Moving locations would change the agents state.
Action any interaction between the agent and enviornment would be considered an action.For example moving to the left or jumping would be
an action.An action may or may not change the current state of the agent.In fact the act of doing nothing is actually an action as well!The
action of s not pressing a key if we are using our mario example.
Reward every action that our agent takes will result in a reward of some magnitude(positive or negative).The goal of our agent will be to
maximize it's reward in an enviomment.Sometimes the reward will be clear, for example if an agent performs an action which increases their
score in the enviomment we could say they've recieved a positive reward.If the agent were to perform an action which results in them losing
score or possibly dying in the enviornment then they would recieve a negative reward.
The most important part of reinforcement learning is determing how to reward the agent.After all,the goal of the agent is to maximize it's
rewards.This means we should reward the agent appropiatly such that it reaches the desired goal.
Q-Learning

# Q-Learning
Now that we have a vague idea of how reinforcement learning works it's time to talk about a specific technique in reinforcement learning
called Q-Learning.
**Q-Learning** is a fairly simple yet quite powerful technique in machine learning that involves learning a matrix of action-reward values.This
matrix is often reffered to as a Q-Table or Q-Matrix.The matrix is in shape(number of possible states, number of possible actions)where each
value at matrix[n,m]represents the agents expected reward given they are in state n and take action m.The Q-learning algorithm defines the
way we update the values in the matrix and decide what action to take at each state.The idea is that after a succesful training/learning of this
Q-Table/matrix we can determine the action an agent should take in any state by looking at that states row in the matrix and taking the
maximium value column as the action.
Consider this example.
Let's say A1-A4 are the possible actions and we have 3 states represented by each row (state 1 -state 3).

A1 A2 A3 A4

0 0 10 5

5 10 00

10 5 0 0


If that was our Q-Table/matrix then the following would be the preffered actions in each state.
State 1 :A3
State 2:A2
State 3:A1
We can see that this is because the values in each of those columns are the highest for those states

# Learning the Q-lable
So that's pretty simple, right? Now how do we create this table and find those values.Well this is where we will dicuss how
the Q-Learning algorithm updates the values in our Q-Table.
I'll start by noting that our Q-Table starts of with all 0 values.This is because the agent has yet to learn anything about the
enviornment.
Our agent learns by exploring the enviornment and observing the outcome/reward from each action it takes in a given
state.But how does it know what action to take in each state?There are two ways that our agent can decide on which
action to take.

1. Randomly picking a valid action

2. Using the current Q-Table to find the best action.

Near the beginning of our agents learning it will mostly take random actions in order to explore the enviornment and enter
many different states.As it starts to explore more of the enviornment it will start to gradually rely more on it's learned
values(Q-Table)to take actions.This means that as our agent explores more of the enviornment it will develop a better
understanding and start to take"correct"or better actions more often.It's important that the agent has a good balance of
taking random actions and using learned values to ensure it does get trapped in a local maxima.
After each new action our agent wil record the new state (if any)that it has entered and the reward that it recieved from
taking that action.These values will be used to update the Q-Table. The agent will stop taking new actions only once a
certain time limit is reached or it has acheived the goal or reached the end of the enviornment.

**Updating Q-Values**
The formula for updating the Q-Table after each action is as follows:

| Q[state,action]= Q[state,action] + a * (reward + y* max(Q[newState, :]) — Q[state,action])

• a(alpha) stands for the Learning Rate
• y(gama) stands for the Discount Factor
**Learning Rate a**

The learning rate a is a numeric constant that defines how much change is permitted on each QTable update.A high
learning rate means that each update will introduce a large change to the current state-action value.A small learning rate
means that each update has a more subtle change. Modifying the learning rate will change how the agent explores
enviornment and how quickly it determines the final values in the QTable.

**Discount Factor y**

Discount factor,also know as gamma(y)is used to balance how much focus is put on the current and future reward.A
high discount factor means that future rewards will be considered more heavily.

To perform updates on this table we will let the agent explore the enviornment for a certain period of time and use each of
its actions to make an update. Slowly we should start to notice the agent learning and choosing better actions.

# Q-Learning Example
For this example we will use the Q-Learning algorithm to train an agent to navigate a popular enviornment from the link text OpenAl Gym.The Open Al Gym was developed so programmers could practice machine learning using unique enviornments.
Intersting fact, Elon Musk is one of the founders of OpenAl!

Let's start by looking at what Open Al Gym is.

In [1]:
import gym

Loading the environment

In [3]:
env = gym.make("FrozenLake-v1") # we are going to use the frozenlake environment

/usr/local/lib/python3.7/dist-packages/gym/core.py:318: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."
/usr/local/lib/python3.7/dist-packages/gym/wrappers/step_api_compatibility.py:40: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."


There are few environments that can be used to interact and get information about the environment.

In [4]:
print(env.observation_space.n)  #get number of states
print(env.action_space.n)  #get number of actions

16
4


In [5]:
env.reset()  #reset environment to default state

0

In [7]:
action = env.action_space.sample() # get a random action

In [8]:
new_state, reward, done, info = env.step(action) # take action, notice it returns information about the action 

In [ ]:
env.render()  # render the GUI for the environment

# Frozen Lake Enviornment
Now that we have a basic understanding of how the gym enviornment works it's time to discuss the specific problem we
will be solving.
The enviornment we loaded above FrozenLake-ve is one of the most simple enviornments in Open Al Gym.The goal of the
agent is to navigate a frozen lake and find the Goal without falling through the ice(render the enviornment above to see an example).
There are:

• 16 states(one for each square)

• 4 possible actions(LEFT,RIGHT, DOWN,UP)

•.4 different types of blocks(F:frozen,H: hole,S:start,G:goal)


# Building the Q-Table
The first thing we need to do is build an empty Q-Table that we can use to store and update our values

In [10]:
import gym
import numpy as np
import time

env = gym.make('FrozenLake-v1')
STATES = env.observation_space.n
ACTIONS = env.action_space.n

/usr/local/lib/python3.7/dist-packages/gym/core.py:318: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."
/usr/local/lib/python3.7/dist-packages/gym/wrappers/step_api_compatibility.py:40: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."


In [11]:
Q = np.zeros((STATES, ACTIONS))
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Constants
As we discussed we need to define some constants that will be used to update our Q-Table and tell our agent when to stop training.

In [12]:
EPISODES = 2000  # how many time to run the enviornment from the begnning 
MAX_STEPS = 100  # max number of steps allowed for each run of the enviornment

LEARNING_RATE = 0.81 # learning rate
GAMA = 0.96

# Picking an Action
Remember that we can pick an action using one of two methods:

1. Randomly picking a valid action

2. Using the current Q-Table to find the best action.

Here we will define a new value&that will tell us the probabillity of selecting a random action.This value will start off very
high and slowly decrease as the agent learns more about the enviornment.

In [13]:
epsilon = 0.9  # start with 90% chance of picking random action

# code to paick the action
if np.random.uniform(0, 1) < epsilon: # we will check if a randomaly selected value is less than epsilon.
  action = env.action_space.sample()  # take random action
else:
  action = np.argmax(Q[state, :]) # use Q to pick best action basef on current values

# Updating the Q Values
The code below implements the formula discussed above.

In [20]:
Q[state, action] = Q[state, action] + LEARNING_RATE * (reward + GAMA * np.max(Q[new_state, :]) - Q[state, action])

In [25]:
RENDER = False
rewards =[]
for episode in range(EPISODES):
  state= env.reset()
  for _ in range(MAX_STEPS):
    if RENDER:
      env.render()
      
    if np.random.uniform(0, 1) < epsilon:
      action =  env.action_space.sample()
      
    else:
      action = np.argmax(Q[state, :])

    next_state, reward, done, _ = env.step(action)

    Q[state, action] = Q[state, action] + LEARNING_RATE * (reward + GAMA * np.max(Q[next_state, :]) - Q[state, action])

    state = next_state 

    if done:
      rewards.append(reward)
      epsilon -= 0.001 
      break # reached the goal
print(Q)
print(f"Average reward: {sum(rewards)/len(rewards)}:")


[[3.32623507e-01 3.14028730e-02 3.22201744e-02 3.07174597e-02]
 [9.28029934e-03 1.52659823e-03 4.83669993e-03 2.20257203e-01]
 [9.01957475e-03 1.95438603e-02 1.06518197e-02 2.85187054e-01]
 [3.94314791e-04 5.52361364e-03 1.23549731e-02 8.18089925e-02]
 [4.57310621e-01 1.53836659e-03 2.10724044e-02 7.28121943e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.27879495e-04 1.50802795e-04 1.37010712e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.32491520e-03 2.19093552e-02 2.05746646e-02 3.33647331e-01]
 [1.35290338e-02 5.04460377e-01 1.91729654e-02 7.64147007e-03]
 [4.79624225e-02 1.81139684e-03 1.48528663e-03 1.02261984e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.88730607e-02 0.00000000e+00 8.43715535e-01 1.59933200e-02]
 [8.70049577e-02 9.76501459e-01 1.06298834e-01 1.03159390e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000